name: flake8 ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Install flake8
      run: pip install flake8 flake8-nb
    - name: run flake8 ⚙️
      run: |
        find . -type f -name "*.py" | xargs flake8
    - name: run flake8-notebook ⚙️
      run: |
        find . -type f -name "*.ipynb" | xargs flake8-nb
